<?php 

$email = <<< email
Dear {$user_email->username},

Somebody has requested that the password associated with this account to be
reset. If you initiated this request, click the below link to complete the process:

http://{$_SERVER['SERVER_NAME']}/auth/recover/key/{$code}

Thank you!
The Album Cd Team

Questions? Contact us at scvroin@yahoo.com or svoicuabg@gmail.com
http://{$_SERVER['SERVER_NAME']}
email;

?>
