<form id="change_password" action="<?= $this->element->getAction(); ?>" enctype="application/x-www-form-urlencoded" method="<?= $this->element->getMethod(); ?>">

<p>
<b>Create a New Password</b>:<br />
<?php echo $this->element->password; ?>
</p>

<p>
<b>Confirm New Password</b>:<br />
<?php echo $this->element->confirm_pswd; ?>
</p>

<p>
<?php echo $this->element->update_password ?>
</p>

</form>